# I'm registering routes like instead of magic methods since its easier to refactor in the future
# and see a general overview

warehouses_create:
    path: warehouses
    controller: App\Warehousing\Http\WarehouseController::create
    methods: [POST]

warehouses_read:
    path: warehouses/{code}
    controller: App\Warehousing\Http\WarehouseController::read
    methods: [ GET ]

warehouses_list:
    path: warehouses
    controller: App\Warehousing\Http\WarehouseController::list
    methods: [ GET ]

warehouses_update:
    path: warehouses/{code}
    controller: App\Warehousing\Http\WarehouseController::update
    methods: [PUT]

warehouses_delete:
    path: warehouses/{code}
    controller: App\Warehousing\Http\WarehouseController::delete
    methods: [ DELETE ]


stock_items_read:
    path: warehouses/{code}/stock/{sku}
    controller: App\Warehousing\Http\StockItemController::read
    methods: [ GET ]
    requirements:
        code: '(?-i)[A-Z0-9._-]{1,32}'
        sku: '(?-i)[A-Z0-9._-]{1,64}'

stock_items_receive:
    path: warehouses/{code}/stock/{sku}/receive
    controller: App\Warehousing\Http\StockItemController::receive
    methods: [ POST ]
    requirements:
        code: '(?-i)[A-Z0-9._-]{1,32}'
        sku: '(?-i)[A-Z0-9._-]{1,64}'

stock_reservations_read:
    path: warehouses/stock/reservations/{number}
    controller: App\Warehousing\Http\StockReservationController::read
    methods: [ GET ]
    requirements:
        code: '(?-i)[A-Z0-9._-]{1,32}'
        number: '(?-i)[A-Z0-9._-]{1,64}'

stock_reservations_create:
    path: warehouses/stock/reservations
    controller: App\Warehousing\Http\StockReservationController::create
    methods: [ POST ]

stock_reservations_ship:
    path: warehouses/stock/reservations/{number}/ship
    controller: App\Warehousing\Http\StockReservationController::ship
    methods: [ POST ]
    requirements:
        number: '(?-i)[A-Z0-9._-]{1,64}'

stock_reservations_cancel:
    path: warehouses/stock/reservations/{number}
    controller: App\Warehousing\Http\StockReservationController::cancel
    methods: [ PUT ]
    requirements:
        number: '(?-i)[A-Z0-9._-]{1,64}'
