# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    # Autowire everything under src/
    App\:
        resource: '../src/'
        exclude:
            - '../src/Kernel.php'

    # Redis autowiring
    Redis:
        class: Redis
        factory: ['Symfony\Component\Cache\Adapter\RedisAdapter', 'createConnection']
        arguments: ['%env(REDIS_URL)%']

    App\Shared\Http\ApiExceptionSubscriber:
        tags: [ 'kernel.event_subscriber' ]

    _instanceof:
        Doctrine\Bundle\FixturesBundle\Fixture:
            tags: ['doctrine.fixture.orm']
    monolog.formatter.allocation_pretty_json:
        class: Monolog\Formatter\JsonFormatter
        arguments:
            $batchMode: !php/const Monolog\Formatter\JsonFormatter::BATCH_MODE_JSON
            $appendNewline: true
            $ignoreEmptyContextAndExtra: false
        calls:
            - [addJsonEncodeOption, [!php/const JSON_PRETTY_PRINT]]
            - [addJsonEncodeOption, [!php/const JSON_UNESCAPED_SLASHES]]
            - [addJsonEncodeOption, [!php/const JSON_UNESCAPED_UNICODE]]
