orders_read:
    path: /orders/{number}
    controller: App\Orders\Http\OrderController::read
    methods: [GET]
    requirements:
        number: '(?-i)[A-Z0-9._-]{1,32}'

orders_list:
    path: /orders
    controller: App\Orders\Http\OrderController::list
    methods: [GET]

orders_create:
    path: /orders/create
    controller: App\Orders\Http\OrderController::create
    methods: [POST]

