<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251031090217 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE warehouses (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code VARCHAR(32) NOT NULL, name VARCHAR(128) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_AFE9C2B777153098 ON warehouses (code)');

        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE stock_items (id UUID NOT NULL, product_sku VARCHAR(64) NOT NULL, on_hand_qty INT NOT NULL, reserved_qty INT NOT NULL, lock_version INT DEFAULT 1 NOT NULL, created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, warehouse_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_7D0EF5BC5080ECDE ON stock_items (warehouse_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_stock_wh_sku ON stock_items (warehouse_id, product_sku)');
        $this->addSql('ALTER TABLE stock_items ADD CONSTRAINT FK_7D0EF5BC5080ECDE FOREIGN KEY (warehouse_id) REFERENCES warehouses (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE warehouses');

        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE stock_items DROP CONSTRAINT FK_7D0EF5BC5080ECDE');
        $this->addSql('DROP TABLE stock_items');
    }
}
